# Generated by Django 2.1.2 on 2018-10-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('user', models.CharField(max_length=160)),
                ('img_url', models.URLField()),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('absolute_url', models.CharField(blank=True, editable=False, max_length=400)),
            ],
        ),
    ]
